version: "1"
services:
  varnish:
    image: eeacms/varnish
    ports:
    - "80:6081"
    - "81:6082"
    environment:
      BACKENDS: "69.164.223.208"
      BACKENDS_PORT: "80"
      DNS_ENABLED: "false"
  web:
    build: ./app
    command: npm start
    volumes:
      - ./app/:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"