apiVersion: v1
kind: Service
metadata:
  name: ui-app
  labels:
    component: server
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30007
  selector:
    component : storage-system-ui
