apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage-systems-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-app-ui
  template:
    metadata:
      labels:
        app: storage-app-ui
    spec:
      containers:
        - name: storage-app-ui
          image: mercykwazi/storageappimage
          ports:
            - containerPort: 80
        