apiVersion: v1
kind: Service
metadata:
  name: storage-systems-ui
  labels:
    app: storage-systems-ui
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30004
  selector:
    app : storage-app-ui