apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage-system-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-system-express
  template:
    metadata:
      labels:
        app: storage-system-express
    spec:
      containers:
        - name: express-app
          image: mercykwazi/api-storage-app
          ports:
            - containerPort: 8081
        