apiVersion: v1
kind: Service
metadata:
  name: express-app
  labels:
    component: server
spec:
  type: NodePort
  ports:
  - port: 8089
    name: http
    nodePort: 30009
  selector:
    component : storage-system-express